name: w3s-proxy
base: core18
version: '1.0.0'
summary: web3.storage proxy
description: web3.storage proxy
grade: stable
confinement: strict
parts:
  web3storage-proxy:
    plugin: go
    source-type: git
    source: https://github.com/itsabgr/w3s-proxy
apps:
  w3s-proxy:
    daemon: simple
    command: bin/w3s-proxy -addr 0.0.0.0:3333
    stop-timeout: 10s
    stop-mode: sigterm
    install-mode: enable
    plugs:
      - network-bind